# Generated by Django 4.2.16 on 2024-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0076_submissionfavourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="custom_speaker_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
