# Generated by Django 4.2.16 on 2024-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0077_submission_custom_speaker_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="etherpad_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
