# Generated by Django 4.2.16 on 2025-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0079_submission_emoji_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="emoji_label",
            field=models.CharField(default="", max_length=255),
        ),
    ]
