# Generated by Django 4.2.16 on 2024-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_public_voting", "0006_publicvotingsettings_limit_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicvote",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="publicvotingsettings",
            name="hide_score",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="publicvote",
            name="score",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
