# Generated by Django 4.2.16 on 2024-11-14 15:00

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_public_voting", "0008_submissionwish_submissionwishvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicvotingsettings",
            name="text_wishes",
            field=i18nfield.fields.I18nTextField(null=True),
        ),
    ]
