# Generated by Django 4.2.23 on 2025-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0045_event_pretix_show_shop_link"),
        ("pretalx_public_voting", "0009_publicvotingsettings_text_wishes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionwish",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="submissionwish",
            unique_together={("event", "name")},
        ),
    ]
