services:
  pretalx:
    build:
      context: .
    container_name: pretalx
    user: "1000:1000"
    restart: always
    depends_on:
      - redis
      - db
    environment:
      # Hint: Make sure you serve all requests for the `/static/` and `/media/` paths when debug is False.
      # See [installation](https://docs.pretalx.org/administrator/installation/#step-7-ssl) for more information
      PRETALX_FILESYSTEM_MEDIA: /pretalx/public/media
      PRETALX_FILESYSTEM_STATIC: /pretalx/public/static #/pretalx/src/static.dist
      PRETALX_FILESYSTEM_LOGS: /pretalx/data/logs
    volumes:
      - ./pyproject.toml:/pretalx/pyproject.toml:ro
      - ./src/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - ./src:/pretalx/src:delegated
    labels:
       traefik.docker.network: "pretalxdocker"
       traefik.enable: "true"

  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: always
    volumes:
      - ./.docker/volumes/db:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: always

