version: '3'
services:
  pretalx:
    build:
      context: .
    container_name: pretalx
    restart: always
    depends_on:
      - redis
      - db
    environment:
      # Hint: Make sure you serve all requests for the `/static/` and `/media/` paths when debug is False.
      # See [installation](https://docs.pretalx.org/administrator/installation/#step-7-ssl) for more information
      PRETALX_FILESYSTEM_MEDIA: /pretalx/public/media
      PRETALX_FILESYSTEM_STATIC: /pretalx/public/static #/pretalx/src/static.dist
      PRETALX_FILESYSTEM_LOGS: /pretalx/data/logs
    ports:
      - "80:80"
    volumes:
      - ./pyproject.toml:/pretalx/pyproject.toml:ro
      - ./src/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - ./.docker/volumes/data:/pretalx/data
      - ./.docker/volumes/public:/pretalx/public
      - ./src:/pretalx/src:delegated
    labels:
       traefik.docker.network: "pretalxdocker"
       traefik.enable: "true"

  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: always
    volumes:
      - ./.docker/volumes/db:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: always

