# Generated by Django 4.2.16 on 2024-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0035_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_api_key",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_identifier_question_participant_list",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
