# Generated by Django 4.2.16 on 2024-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0036_event_pretix_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_api_domain",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_api_event_slug",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_api_organisator_slug",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
