# Generated by Django 4.2.16 on 2024-10-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0037_event_pretix_api_domain_event_pretix_api_event_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_identifier_question_submission_wishes",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
