# Generated by Django 4.2.16 on 2024-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0038_event_pretix_identifier_question_submission_wishes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_firstname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_lastname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_organisation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_participant_list_postcode",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
