# Generated by Django 4.2.16 on 2024-10-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_event_pretix_qid_participant_list_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_qid_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_organisation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="pretix_qid_postcode",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
