# Generated by Django 4.2.16 on 2024-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0040_event_pretix_qid_city_event_pretix_qid_organisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_qid_country",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
