# Generated by Django 4.2.16 on 2024-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0042_event_venueless_domain_event_venueless_embed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="survey_merger_pretix_qid_whitelist",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
