# Generated by Django 4.2.16 on 2025-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0043_event_survey_merger_pretix_qid_whitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_website_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
