# Generated by Django 4.2.16 on 2025-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0044_event_event_website_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix_show_shop_link",
            field=models.BooleanField(default=False),
        ),
    ]
